/* =========================================================
   01. DATABASE SETUP & DATA LOADING
   ========================================================= */

create database pharma_db;
use pharma_db;

create table pharmacy_data 
         (Transaction_ID int primary key,
         Transaction_Date date,
         Branch_ID int,
         Branch_Name varchar(200),
         District varchar(50),
         Province varchar(50),
         Payment_Method varchar(50),
         Customer_Gender varchar(20),
         Customer_Age int,
         Customer_City varchar(50),
         Medicine_ID int,
         Medicine_Name varchar(200),
         Generic_Name varchar(50),
         Medicine_Category varchar(50),
         Dosage_Form varchar(50),
         Strength_mg int,
         Pack_Size int,
         Supplier_Name varchar(100),
         Prescription_Required varchar(20),
         Batch_No varchar(20),
         Expiry_Date date,
         Quantity int,
         Unit_Price_LKR float,
         Discount_Rate float,
         Line_Total_LKR float,Year int, Month int
	);


load data infile "C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Pharmacy_OLTP_SLStyle_18Months.csv" into table pharmacy_data fields terminated by ',' enclosed by '"' lines terminated by '\n' ignore 1 rows
(Transaction_ID,
@Transaction_Date,
Branch_ID,
Branch_Name,
District,
Province,
Payment_Method,
Customer_Gender,
Customer_Age,
Customer_City,Medicine_ID,Medicine_Name,Generic_Name,Medicine_Category,Dosage_Form,
@Strength_mg,
Pack_Size,Supplier_Name,Prescription_Required,Batch_No,
@Expiry_Date,
Quantity,Unit_Price_LKR,Discount_Rate,Line_Total_LKR,
Year,Month)
set Strength_mg = NULLIF(@Strength_mg, ""),
	Transaction_Date = STR_TO_DATE(@Transaction_Date, '%m/%d/%Y'),
    Expiry_Date = STR_TO_DATE(@Expiry_Date, '%m/%d/%Y');
    

/* =========================================================
   02. DATA CLEANING & VALIDATION
   ========================================================= */


##1. Checking for the missing values
SELECT
    COUNT(*) AS total_rows,
    SUM(Transaction_Date IS NULL) AS missing_transaction_date,
    SUM(Branch_ID IS NULL) AS missing_branch,
    SUM(Medicine_ID IS NULL) AS missing_medicine,
    SUM(Quantity IS NULL) AS missing_quantity,
    SUM(Unit_Price_LKR IS NULL) AS missing_price,
    SUM(Line_Total_LKR IS NULL) AS missing_line_total
FROM pharmacy_data;

## 2. Quantity Validation

SELECT * FROM pharmacy_data
WHERE Quantity <=0;

## 2. Price Validation

SELECT * FROM pharmacy_data
WHERE Unit_Price_LKR <=0;

## 3. Date Exploration

SELECT 
MIN(Transaction_Date) as First_Transaction,
MAX(Transaction_Date) as Last_Transaction,
MIN(Expiry_Date) as Earliest_Expiry,
MAX(Expiry_Date) as Latest_Expiry
FROM pharmacy_data;

## 4. Checking the line total calculation

SELECT
Transaction_ID,
Quantity,
Unit_Price_LKR,
Discount_Rate,
Line_Total_LKR,
ROUND(Quantity * Unit_Price_LKR * (1- Discount_Rate),2)
FROM pharmacy_data;

select * from pharmacy_data;


/* =========================================================
   03. KEY PERFORMANCE INDICATORS
   ========================================================= */
 
 -- Calculate total revenue generated by the pharmacy during the analysis period.
   
select 
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data;

-- Calculate the total transactions of medicines  during the analysis period.

select
count(Transaction_Id) as Total_Transactions
from pharmacy_data;

-- Calculate the average transaction value to understand the average revenue generated per transaction.

with transact_revenue as
(
select 
count(Transaction_Id) as Total_Transactions,
sum(Line_Total_LKR) as Revenue
from pharmacy_data
)
select 
round(avg(Revenue/Total_Transactions),2) as Avg_Transaction_Value
from transact_revenue;

-- Measure the discount-to-revenue ratio to evaluate the contribution of discounts to pharmacy sales.

with discount as
(
select
sum(quantity*Unit_Price_LKR) as Gross_Revenue,
sum(Quantity * Unit_Price_LKR*Discount_Rate) as Total_Discount
from pharmacy_data
)
select
 concat(Round(Total_Discount/Gross_Revenue * 100, 1),"%") as Discount_To_Revenue_Ratio
from discount ;


/* =========================================================
   04. CUSTOMER ANALYSIS
   ========================================================= */
   
 
 -- Compare pharmacy revenue across customer genders to understand differences in sales contribution.

select 
Customer_Gender,
count(*) as Total_Customers,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by Customer_Gender;

-- Identify the cities contributing the highest number of pharmacy transactions.

select 
Customer_City,
count(*) as Total_Customers_By_City
from pharmacy_data
group by Customer_City
order by Total_Customers_By_City desc;

-- Analyze revenue across customer age groups to identify the groups contributing most to sales.

with customer_segment as
(
select 
Customer_Age,
case
    when Customer_Age > 0 and Customer_Age <= 10 then "Child"
    when Customer_Age >= 11 and Customer_Age <= 17 then "Tennager"
    when Customer_Age >= 18 and Customer_Age <=25 then "Young Adult"
    when Customer_Age >= 26 and Customer_Age <= 49 then "Adult"
    when Customer_Age >= 50 and Customer_Age <=65 then "Senior"
    else "Elderly"
    end as Customer_Segment
from pharmacy_data
)
select
Customer_Segment,
count(*) as Total_Customer_By_Segment
from Customer_Segment
group by Customer_Segment
order by Total_Customer_By_Segment desc; 

-- Compare payment methods by transaction volume and revenue to understand customer payment preferences.

select 
payment_method,
count(*) as Payment_Used,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by payment_method
order by Payment_Used, Revenue desc;


/* =========================================================
   05. MEDICINE ANALYSIS
   ========================================================= */
   
-- Compare medicine categories by revenue and quantity to identify the categories contributing most to pharmacy sales.

select
Medicine_Category,
sum(Quantity) as Total_Quantity,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by Medicine_Category
order by Total_Quantity, Revenue desc;

-- Identify the top 10 medicines generating the highest revenue to understand the pharmacy's major revenue contributors.

select 
Medicine_Name,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by Medicine_Name
order by Revenue desc limit 10;

-- Identify the top 10 medicines with the highest quantities sold to understand product demand by sales volume.

select 
Medicine_Name,
sum(Quantity) as Total_Quantity
from pharmacy_data
group by Medicine_Name
order by Total_Quantity desc limit 10;

-- Analyze medicine sales volume across provinces and dosage forms to identify differences in product demand.

select
Province,
Dosage_Form,
sum(Quantity) as Total_Quantity
from pharmacy_data
group by province, dosage_form;

-- Compare prescription-required and non-prescription medicines by transaction volume and revenue contribution.

with prescription_cal as
(
select
prescription_required,
count(*) as Total_Count,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by prescription_required
)
select 
prescription_required,
concat(round(Total_Count/(select count(*) from pharmacy_data)*100,2),"%") as Count_Percent,
concat(round(Revenue/(select sum(Line_Total_LKR) from pharmacy_data) * 100,2), "%") as Revenue_Percent
from prescription_cal
group by prescription_required;


/* =========================================================
   06. REVENUE & GROWTH ANALYSIS
   ========================================================= */
   
   

with y_m_analysis as
(
select 
year, month,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by year, month
)
, M_o_M as 
(
select 
year,
month,
Revenue,
lag(Revenue) over(order by month) as Previous_revenue
from y_m_analysis
)
select 
year,
month,
concat(round((Previous_Revenue - Revenue)/ Previous_Revenue * 100, 1), "%") as M_o_M_Growth
from M_o_M
order by year;


/* =========================================================
   07. SUPPLIER & INVENTORY ANALYSIS
   ========================================================= */
   
   
select 
supplier_name, Medicine_Category,
sum(Quantity) as Total_Quantity,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by supplier_name, Medicine_Category
order by Total_Quantity, Revenue;

with supplier_cte as
(
select
supplier_name,
round(sum(Line_Total_LKR),2) as Revenue
from pharmacy_data
group by supplier_name
) 
select
supplier_name,
concat(round(Revenue/ (select round(sum(Line_Total_LKR),2) from pharmacy_data) *100, 1), "%") as Supplier_percent
from supplier_cte
order by Supplier_percent desc;


/* =========================================================
   08. PRODUCT EXPIRY RISK ANALYSIS
   ========================================================= */
   

with days_cte as
(
select 
datediff(Expiry_Date, Transaction_Date) as Days_To_Expire,
Line_Total_LKR
from pharmacy_data
) 
, segment_cte as
(
select 
Days_To_Expire,
Line_Total_LKR,
case 
    when Days_To_Expire < 0 then "Expired at Sale"
    when Days_To_Expire > 0 and Days_To_Expire < 90 then "High Risk"
    when Days_To_Expire >= 90 and Days_To_Expire <= 180 then "Moderate Risk"
    else "Safe"
    end as Expiry_Days_Segment
from days_cte
)
select 
Expiry_Days_Segment,
round(sum(Line_Total_LKR),2) as Revenue,
count(*) as Transaction_Count
from segment_cte
group by Expiry_Days_Segment;






